rainbowColor = 10
xSize=10
library(shiny)
library(datasets)

setFromAndToDates("2001-01-01", "2015-01-01")
xColoumnG= "Type"
yColoumnG= "ClientID"
xG = getTwoDimensionalMatrixFromElasticsearch(xColoumnG)
yG=  getTwoDimensionalMatrixFromElasticsearch(yColoumnG)
fixY = as.matrix(yG[1,1])

#x vs count - two dimensional
barplot(as.numeric(xG[,2]), main=xColoumnG, xlab=xColoumnG, ylab="Count", col=rainbow(rainbowColor) )
#pie(as.numeric(xG[,2]), main=xColoumnG, xlab=xColoumnG, ylab="Count", col=rainbow(rainbowColor), labels=paste(xG[,1]) )
legend("topright", legend=paste(xG[,1]), fill=rainbow(rainbowColor))
#y's own top xs
xGsYEL = getXsMatrixFromElasticsearch(fixY, xColoumnG, yColoumnG)
barplot(as.numeric(xGsYEL[2,]), main=paste(xColoumnG,"vs", yColoumnG,fixY), xlab= xColoumnG, ylab= "Count", names.arg=xGsYEL[1,], col=rainbow(rainbowColor))
legend("topright", legend=paste(xGsYEL[1,]), fill=rainbow(rainbowColor))
#CFL top xs count for fixed y
xGsYEL_Of_Top_Xs = getXYsMatrixFromElasticsearch(xG, fixY, xColoumnG, yColoumnG)
barplot(as.numeric(xGsYEL_Of_Top_Xs[1,]), main=paste(yColoumnG,"vs Count for ", fixY), xlab= xColoumnG, ylab= "Count", names.arg=xG[,1], col=rainbow(rainbowColor))
legend("topright", legend=paste(xG[,1]), fill=rainbow(rainbowColor))
#CFL top xs vs CFL top ys matrix - three dimensional
xsysMatrixEL = getXYsMatrixFromElasticsearch(xG, yG, xColoumnG, yColoumnG)
barplot(xsysMatrixEL, main=paste(xColoumnG, "s"," vs ", yColoumnG, "s", sep=""), xlab= xColoumnG, ylab= "Count", beside=TRUE, names.arg=xG[,1], col=rainbow(rainbowColor))
legend("topright", legend=paste(yG[,1]), fill=rainbow(rainbowColor))

coloumns = list("AdministrativeArea" = "AdministrativeArea",
                "AllWrongNamesSameAsNewName" = "AllWrongNamesSameAsNewName",
                "AnomalyCategory" = "AnomalyCategory",
                "AnomalyID" = "AnomalyID",
                "Application" = "Application",
                "BlockageEndDate" = "BlockageEndDate",
                "BlockageStartDate" = "BlockageStartDate",
                "BlockedPassageType" = "BlockedPassageType",
                "CaseID" = "CaseID",
                "Category" = "Category",
                "CategoryDescription" = "CategoryDescription",
                "CenterPointAdminAreaOrder1" = "CenterPointAdminAreaOrder1",
                "CenterPointAdminAreaOrder2" = "CenterPointAdminAreaOrder2",
                "CenterPointAdminAreaOrder7" = "CenterPointAdminAreaOrder7",
                "CenterPointAdminAreaOrder8" = "CenterPointAdminAreaOrder8",
                "CenterPointAdminAreaOrder9" = "CenterPointAdminAreaOrder9",
                "CenterPointContinent" = "CenterPointContinent",
                "CenterPointCountry" = "CenterPointCountry",
                "CenterPointDataSet" = "CenterPointDataSet",
                "CenterPointTier" = "CenterPointTier",
                "CenterPointTierName" = "CenterPointTierName",
                "CenterPointVia" = "CenterPointVia",
                "CenterPointViaName" = "CenterPointViaName",
                "City" = "City",
                "ClientID" = "ClientID",
                "Comments" = "Comments",
                "ConsideredByCaseJourneyman" = "ConsideredByCaseJourneyman",
                "Country" = "Country",
                "CreationDate" = "CreationDate",
                "CustomerReferenceID" = "CustomerReferenceID",
                "DestinationAdministrativeArea" = "DestinationAdministrativeArea",
                "DestinationCity" = "DestinationCity",
                "DestinationCountry" = "DestinationCountry",
                "DestinationStreetAddress" = "DestinationStreetAddress",
                "DuplicateStretchPoints" = "DuplicateStretchPoints",
                "EmailAddress" = "EmailAddress",
                "Endorsement" = "Endorsement",
                "FeatureID" = "FeatureID",
                "FOW" = "FOW",
                "FRC" = "FRC",
                "FRCA" = "FRCA",
                "FromStreetName" = "FromStreetName",
                "Gated" = "Gated",
                "GeoAugmentationDataVersion" = "GeoAugmentationDataVersion",
                "GeoAugTag" = "GeoAugTag",
                "GeocodedAddress" = "GeocodedAddress",
                "GUID" = "GUID",
                "HasMapShareEmailAddress" = "HasMapShareEmailAddress",
                "HouseNumber" = "HouseNumber",
                "IncidentStatus" = "IncidentStatus",
                "IncidentStatusReason" = "IncidentStatusReason",
                "InfoBlob" = "InfoBlob",
                "IrisProjectName" = "IrisProjectName",
                "LaneCount" = "LaneCount",
                "Language" = "Language",
                "LatestCommunityUserSentTo" = "LatestCommunityUserSentTo",
                "LatestCommunityUserSourcedFrom" = "LatestCommunityUserSourcedFrom",
                "LatestStatusUpdateDate" = "LatestStatusUpdateDate",
                "LatestStatusUpdater" = "LatestStatusUpdater",
                "LatestStatusUpdaterType" = "LatestStatusUpdaterType",
                "Magnitude" = "Magnitude",
                "MaxLat" = "MaxLat",
                "MaxLon" = "MaxLon",
                "MinLat" = "MinLat",
                "MinLon" = "MinLon",
                "Name" = "Name",
                "NavCoreVersion" = "NavCoreVersion",
                "NavigationProductVersion" = "NavigationProductVersion",
                "NumberOfCrossingStreetNames" = "NumberOfCrossingStreetNames",
                "NumberOfStretches" = "NumberOfStretches",
                "Opinion" = "Opinion",
                "OpinionCreationDate" = "OpinionCreationDate",
                "OpinionDataVersion" = "OpinionDataVersion",
                "OpinionInsertDate" = "OpinionInsertDate",
                "OpinionMatchCount" = "OpinionMatchCount",
                "OpinionMessageCode" = "OpinionMessageCode",
                "OpinionMessageDetails" = "OpinionMessageDetails",
                "OpinionTifSchema" = "OpinionTifSchema",
                "OpinionUpdater" = "OpinionUpdater",
                "OpinionUpdaterVersion" = "OpinionUpdaterVersion",
                "OriginAdministrativeArea" = "OriginAdministrativeArea",
                "Originator" = "Originator",
                "OriginCity" = "OriginCity",
                "OriginCountry" = "OriginCountry",
                "OriginStreetAddress" = "OriginStreetAddress",
                "Owner" = "Owner",
                "PartitionID" = "PartitionID",
                "POIEMailAddress" = "POIEMailAddress",
                "POIFaxNumber" = "POIFaxNumber",
                "POIId" = "POIId",
                "POIPlaceOwner" = "POIPlaceOwner",
                "POITelephoneNumber" = "POITelephoneNumber",
                "POIWebSite" = "POIWebSite",
                "POIWrongLocated" = "POIWrongLocated",
                "Postcode" = "Postcode",
                "PredictedDTRF" = "PredictedDTRF",
                "Priority" = "Priority",
                "ProblemDataVersion" = "ProblemDataVersion",
                "ProblemRepresentative" = "ProblemRepresentative",
                "ProductDescription" = "ProductDescription",
                "ProductVersionActual" = "ProductVersionActual",
                "ProductVersionPlanned" = "ProductVersionPlanned",
                "ProposedSpeedLimitNEG" = "ProposedSpeedLimitNEG",
                "ProposedSpeedLimitPOS" = "ProposedSpeedLimitPOS",
                "Reformed" = "Reformed",
                "RemovableBlockageType" = "RemovableBlockageType",
                "ReportingOpinion" = "ReportingOpinion",
                "ReportingOpinionDataVersion" = "ReportingOpinionDataVersion",
                "ReportingOpinionThrownDate" = "ReportingOpinionThrownDate",
                "ReportingOpinionUpdateDate" = "ReportingOpinionUpdateDate",
                "RestrictionUnitsBackward" = "RestrictionUnitsBackward",
                "RestrictionUnitsForeward" = "RestrictionUnitsForeward",
                "RestrictionValueBackward" = "RestrictionValueBackward",
                "RestrictionValueForeward" = "RestrictionValueForeward",
                "SalesRegion" = "SalesRegion",
                "SentToCommunityUser" = "SentToCommunityUser",
                "ServerName" = "ServerName",
                "SolveMethod" = "SolveMethod",
                "SourcedFromCommunityUser" = "SourcedFromCommunityUser",
                "SpeedLimit" = "SpeedLimit",
                "SpeedLimitUnit" = "SpeedLimitUnit",
                "Status" = "Status",
                "StreetAddress" = "StreetAddress",
                "StreetName" = "StreetName",
                "SubCategory" = "SubCategory",
                "SubCategoryDescription" = "SubCategoryDescription",
                "SubmissionDate" = "SubmissionDate",
                "SubStatus" = "SubStatus",
                "TAFeedback" = "TAFeedback",
                "ThirdPartyfied" = "ThirdPartyfied",
                "Thrown" = "Thrown",
                "ThrownDate" = "ThrownDate",
                "ThrownTo" = "ThrownTo",
                "TifDTRF" = "TifDTRF",
                "ToStreetName" = "ToStreetName",
                "TotalStretchPointCount" = "TotalStretchPointCount",
                "TPIReportCreationDate" = "TPIReportCreationDate",
                "TransferredDate" = "TransferredDate",
                "Trust" = "Trust",
                "Type" = "Type",
                "UpdateReportDatabase" = "UpdateReportDatabase",
                "UpdateReportIDs" = "UpdateReportIDs",
                "UserId" = "UserId",
                "UserStatus" = "UserStatus",
                "UserSuppliedURL" = "UserSuppliedURL",
                "Validity" = "Validity",
                "ValidityCreationDate" = "ValidityCreationDate",
                "ValidityInsertDate" = "ValidityInsertDate",
                "ValidityMessageCode" = "ValidityMessageCode",
                "ValidityMessageDetails" = "ValidityMessageDetails",
                "ValiditySourceVersion" = "ValiditySourceVersion",
                "ValidityThrownDate" = "ValidityThrownDate",
                "ValidityUpdater" = "ValidityUpdater",
                "ValidityUpdaterVersion" = "ValidityUpdaterVersion",
                "VehicleBrand" = "VehicleBrand",
                "VehicleModel" = "VehicleModel",
                "VehicleType" = "VehicleType",
                "VehicleYear" = "VehicleYear",
                "WrongAdministrativeArea" = "WrongAdministrativeArea",
                "WrongCategory" = "WrongCategory",
                "WrongCategoryDescription" = "WrongCategoryDescription",
                "WrongCenterPoint" = "WrongCenterPoint",
                "WrongCity" = "WrongCity",
                "WrongHouseNumber" = "WrongHouseNumber",
                "WrongName" = "WrongName",
                "WrongPOIEMailAddress" = "WrongPOIEMailAddress",
                "WrongPOIFaxNumber" = "WrongPOIFaxNumber",
                "WrongPOITelephoneNumber" = "WrongPOITelephoneNumber",
                "WrongPOIWebSite" = "WrongPOIWebSite",
                "WrongPostcode" = "WrongPostcode",
                "WrongSpeedLimit" = "WrongSpeedLimit",
                "WrongStreetName" = "WrongStreetName",
                "WrongSubCategory" = "WrongSubCategory",
                "WrongSubCategoryDescription" = "WrongSubCategoryDescription"
)
